use_frameworks!

platform :ios, '8.0'

target 'TCBaseModule_Example' do
  pod 'TCBaseModule', :path => '../'

  target 'TCBaseModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
